version: '3.8'

services:
  backend:
    build: .
    container_name: mocvi_backend
    restart: always
    # Ports removed to force traffic through Nginx
    # ports:
    #   - "80:8080"
    expose:
      - "8080"
    volumes:
      - ./docker_data:/app/DbStorage
      - ./docker_data/images:/app/wwwroot/images
      - ./dataprotection-keys:/app/dataprotection-keys
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - AI__ApiUrl=http://ai-service:8000
    env_file:
      - .env
    depends_on:
      - ai-service
      - redis

  nginx:
    image: nginx:alpine
    container_name: mocvi_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    container_name: mocvi_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  ai-service:
    build: ./Trainning_AI
    container_name: mocvi_ai
    restart: always
    volumes:
      - ./docker_data:/app/DbStorage
    environment:
      - PORT=8000
      - HOST=0.0.0.0
    env_file:
      - .env

  redis:
    image: redis:alpine
    container_name: mocvi_redis
    restart: always
    volumes:
      - ./docker_data/redis:/data
    ports:
      - "6379:6379"

volumes:
  redis_data:
